#!/bin/bash
#
# Author: Chris King, Michael Davis, Sam Doerr
#
# chkconfig: 2345 13 87
# description: IFIDS is an Intranet Firewall and Intrusion Detection \
# 	       System, which is quick to install, easy to customize, and very scalable
#
#
#   Intranet Firwall and Intrusion Detection System (IFIDS)    
#   Copyright (C) 2012  Christopher King, Michael Davis, Sam Doerr
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see http://www.gnu.org/licenses/
#
#   For more information, contact Christopher King at ccking@smu.edu





DAEMON="/usr/sbin/ifids/ifids_daemon"
NAME="ifids_daemon"
PIDFILE="/var/run/$NAME.pid"
LOCKFILE="/var/lock/$NAME"

if [ $EUID -ne 0 ]
then
	echo "   Error: Must be run as root"
	exit 1
fi

do_start()
{
	echo -n "   Starting IFIDS: "
	if [ -a $PIDFILE ]
	then
		echo "[ Already running.  PID: `cat $PIDFILE` ]"
		exit 1;
	fi
	if [ -a $DAEMON ]
	then
		$DAEMON &> /dev/null
		if [ $? == 0 ]
		then
			echo "[ Success ]"
			touch $LOCKFILE
		else
			echo "[ Fail ]"
		fi
	else
		echo "[ No IFIDS Daemon found. Is it installed? ]"
	fi
}

do_stop()
{
	echo -n "   Stopping IFIDS: "
	if [ -a $PIDFILE ]
	then
		PID=`cat $PIDFILE`
		if ps $PID | grep ifids &> /dev/null
		then
			kill $PID
			if [ $? == 0 ]
			then
				echo "[ Success ]"
				rm -f $PIDFILE
				rm -f $LOCKFILE
			else
				echo "[ Fail] "
			fi
		else
			rm -f $PIDFILE
			rm -f $LOCKFILE
			echo "[ Not running ]"
		fi
	else
		PID=`ps aux | grep -v grep | grep $DAEMON | awk '{print $2}'`
		if [[ $PID -ne "" ]]
		then
			kill $PID
			if [ $? == 0 ]
			then
				echo "[ Success ]"
				rm -f $LOCKFILE
			else
				echo "[ Fail ]"
			fi
		else
			rm -f $LOCKFILE
			echo "[ Not running ]"
		fi
	fi
	
	if lsmod | grep ifids &> /dev/null
	then
		rmmod ifids_module;
		if [ $? != 0 ]
		then
			echo "[ Failed to remove module ]"
		fi
	fi
}


case "$1" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	restart)
		do_stop
		do_start
		;;
	*)
		echo "   Usage: {start|stop|restart}"
		exit 1
		;;
esac
exit $?


















